Repository drinksandco/symfony-console-ui, pull requests merged in 2022-10, with the labels that each got.

#32 Fixed console-ui bundle readme grammar
  README.md
Labels: documentation, hacktoberfest

#33 [#29] setup repo for recipe installation
  README.md
  composer.json
  src/Command/StartConsoleUiCommand.php
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#35 [#16] define our mercure hub service
  README.md
  assets/components/TestCase.ts
  composer.json
  src/Command/StartConsoleUiCommand.php
  src/ConsoleUiBundle.php
  src/DependencyInjection/ConsoleUiExtension.php
  tests/DependencyInjection/ConsoleUiExtensionTest.php
Labels: bug, documentation, enhancement, hacktoberfest
